# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3efed5aa2c0df631980aed03433c95a55ac93b57b27431f2ae342b2ca7798c850d4ccbd90ef956667cf638c328be655297d561ce3b0fdb4196bb28a7d20b9e99

test:
  secret_key_base: 6a765093a583af1d0b9dc3a4af32a889f84e04a20f111ee48e63ff2a937cd708f49701a87185443b22bc5aebc5fd91a20254d84110b31df72d99245dbd28a87f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
